#Aloha 解锁 Premium VPN(Mainland无法使用)
#测试版本v4.0.1
#@Marol62926

hostname = api.alohaprofile.com

https://api.alohaprofile.com/v1/profile_info url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/aloha.js
