# Aloha 解锁 Premium VPN(Mainland无法使用)
# 测试版本v4.0.1
# @Marol62926

hostname = api.alohaprofile.com

https://api.alohaprofile.com/v1/profile_info url response-body "end_of_premium":.*?, response-body "end_of_premium":1673508929,
https://api.alohaprofile.com/v1/profile_info url response-body "_end_of_premium":.*?, response-body "_end_of_premium":"2023-01-12 15:35:29",
https://api.alohaprofile.com/v1/profile_info url response-body "is_premium":.*?, response-body "is_premium":true,
