hostname = e.dangdang.com

https://e.dangdang.com/media/api2.go url response-body "monthlyEndTime":\w*\w, response-body "monthlyEndTime": 1681105058000,
https://e.dangdang.com/media/api2.go url response-body "isVip": \d, response-body "isVip": 1,
