# Flo女性日记 解锁 高级版
# 测试版本v8.11
# @Marol62926

hostname = api.owhealth.*

https://api.owhealth.(com|cn)/subscriptions/v1/apple url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/flo.js
