hostname = api.midukanshu.com,api.midureader

https://api.midureader.com/fiction/user/getInfo url response-body "isVip":.*?, response-body "isVip": 1,
https://api.midukanshu.com/user/relation/vipAndGoodsV2 url response-body "isVip":.*?, response-body "isVip": 1,
https://api.midureader.com/fiction/user/getInfo url response-body "vip_end_time":.*?" response-body "vip_end_time": "2029-04-16 20:18:18"
https://api.midureader.com/wz/user/* url response-body "vip_end_time":.*?" response-body "vip_end_time": "2029-04-16 20:18:18"
https://api.midukanshu.com/user/relation/vipAndGoodsV2 url response-body "vip_end_time":.*?" response-body "vip_end_time": "2029-04-16 20:18:18"
https://api.midureader.com/fiction/user/getInfo url response-body "endTime":.*?, response-body "endTime": "2029-04-16 20:18:18",
https://api.midureader.com/fiction/user/getInfo url response-body "end_time":.*?, response-body "end_time": "2029-04-16 20:18:18",

