#解锁 Nebula vip
#测试版本v4.24.0
hostname = zh-api.nebulahoroscope.com

https://zh-api.nebulahoroscope.com/api/v7/users/19322278/premium url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/Nebula.js
