hostname = api.revenuecat.com

# noto
^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[a-zA-Z0-9_-]*$) url script-response-body https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Script/noto.js