# Quizlet 解锁 Plus
# 测试版本v6.19
# @Marol62926

hostname = api.quizlet.com

https://api.quizlet.com/3.8/users/* url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/quizlet.js
