hostname=pro-status-service-prod.azurewebsites.net

# ～ RNI高级会员
https://pro-status-service-prod.azurewebsites.net/api/item url script-response-body https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Crack/rf.js
