#解锁飒漫画vip，需要登陆
#测试版本v3.5.3
hostname = m.samh.xndm.tech

#解锁会员状态
https://m.samh.xndm.tech/userapi/info/v1/getuserinfo url response-body "isvip":.*?, response-body "isvip":1,
https://m.samh.xndm.tech/api/v1/vip/home_page url response-body "expire_time":.*?, response-body "expire_time": 4084780884,
https://m.samh.xndm.tech/api/v1/vip/home_page url response-body "diamond_expire_time":.*?, response-body "diamond_expire_time": 4084780884,
#去除购买错误和参数错误提示
https://m.samh.xndm.tech/api/v1/comics/purchase_chapters_diamonds_coin url response-body "msg":.*?, response-body "msg":,
#去广告
https://pangolin.snssdk.com/api/ad/union/sdk/get_ads/ url reject-200
