hostname = m.samh.xndm.tech

#解锁会员状态
https://m.samh.xndm.tech/userapi/info/v1/getuserinfo url response-body "isvip":.*?, response-body "isvip":1,
#去除购买错误和参数错误提示
https://m.samh.xndm.tech/api/v1/comics/purchase_chapters_diamonds_coin url response-body "msg":.*?, response-body "msg":,
