hostname = app.lalaldc.cn

https://app.lalaldc.cn/api/lifan-customer/customer/info url response-body "isvip":.*?, response-body "isvip": 1,
https://app.lalaldc.cn/api/lifan-customer/customer/info url response-body "vipStatus":.*?, response-body "vipStatus": 1,
https://app.lalaldc.cn/api/lifan-customer/customer/info url response-body "vipEndDate":.*?, response-body "vipEndDate": "2029-01-01",
https://app.lalaldc.cn/api/lifan-customer/customer/info url response-body "vipEndDateTime":.*?, response-body "vipEndDateTime": "2029-01-01 10:19:38",
