# vsco解锁vip
# 测试版本v264.0(商店最新版)
# @Marol62926

hostname = api.revenuecat.com

https://api.revenuecat.com/v1/subscribers url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/vsco.js
