hostname = api.revenuecat.com

https://api.revenuecat.com/v1/receipts url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/Widgetsmith.js
https://api.revenuecat.com/v1/subscribers/* url script-response-body https://raw.githubusercontent.com/Marol62926/MarScrpt/main/Widgetsmith.js
