hostname = api.revenuecat.com

https://api.revenuecat.com/v1/subscribers/* url response-body "Premium":.*?} response-body "Premium": {
        "expires_date":"2029-05-26T05:05:04Z",
        "grace_period_expires_date": null,
        "product_identifier": "PremiumMonthly",
        "purchase_date":"2022-04-09T05:05:04Z"
      }
https://api.revenuecat.com/v1/subscribers/* url response-body "subscriptions":.*?}} response-body "subscriptions": {
      "PremiumMonthly": {
        "billing_issues_detected_at": null,
        "expires_date": "2029-05-26T05:05:04Z",
        "grace_period_expires_date": null,
        "is_sandbox": false,
        "original_purchase_date": "2022-04-12T12:54:03Z",
        "ownership_type": "PURCHASED",
        "period_type": "trial",
        "purchase_date": "2022-04-12T12:54:03Z",
        "store": "app_store",
        "unsubscribe_detected_at": null
      }
    }
