hostname = mobwsa.ximalaya.com, m.ximalaya.com, hybrid.ximalaya.com
#喜马拉雅VIP
^https:\//mobwsa.ximalaya.com\/mobile-user\/v1\/homePage url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/homepage.js
^https:\//m.ximalaya.com\/business-vip-presale-core-web\/product\/info url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/vip.js
^http:\//m.ximalaya.com\/vip\/check\/user url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/vipcheck.js
^http:\//mwsa.ximalaya.com\/vip\/check\/user url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/vipcheck.js
^https:\//mobwsa.ximalaya.com\/vip\/v1\/recommand\/ts url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/ts.js
^https:\//m.ximalaya.com\/business-vip-level-h5-web\/api\/profile url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/profile.js
^http:\//hybrid.ximalaya.com\/web-activity\/task\/taskRecords url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/task.js
^http:\//hybrid.ximalaya.com\/hybrid\/api\/newUserWelfare\/participateInfo url script-response-body https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/xmly/part.js
^https:\/\/adse.+.com\/[a-z]{4}\/loading\?appid= url reject
^https:\/\/adse.ximalaya.com\/ting\/feed\?appid= url reject
^https:\/\/adse.ximalaya.com\/ting\/loading\?appid= url reject
^https:\/\/adse.ximalaya.com\/ting\?appid= url reject
^https:\/\/fdfs.xmcdn.com\/group21\/M03\/E7\/3F\/ url reject
^https:\/\/fdfs.xmcdn.com\/group21\/M0A\/95\/3B\/ url reject
^https:\/\/fdfs.xmcdn.com\/group22\/M00\/92\/FF\/ url reject
^https:\/\/fdfs.xmcdn.com\/group22\/M05\/66\/67\/ url reject
^https:\/\/fdfs.xmcdn.com\/group22\/M07\/76\/54\/ url reject
^https:\/\/fdfs.xmcdn.com\/group23\/M01\/63\/F1\/ url reject
^https:\/\/fdfs.xmcdn.com\/group23\/M04\/E5\/F6\/ url reject
^https:\/\/fdfs.xmcdn.com\/group23\/M07\/81\/F6\/ url reject
^https:\/\/fdfs.xmcdn.com\/group23\/M0A\/75\/AA\/ url reject
^https:\/\/fdfs.xmcdn.com\/group24\/M03\/E6\/09\/ url reject
^https:\/\/fdfs.xmcdn.com\/group24\/M07\/C4\/3D\/ url reject
^https:\/\/fdfs.xmcdn.com\/group25\/M05\/92\/D1\/ url reject
